"""Add first_name, last_name, middle_name to students table

Revision ID: 0a6b8fac5558
Revises: 913618fd2a51
Create Date: 2025-06-22 02:04:04.789569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6b8fac5558'
down_revision = '913618fd2a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=100), nullable=True))
    
    # Update existing records to populate the new fields from the existing 'name' field
    connection = op.get_bind()
    
    # Use PostgreSQL-compatible string functions
    connection.execute(sa.text("""
        UPDATE students 
        SET first_name = CASE 
                WHEN name IS NOT NULL AND trim(name) != '' THEN 
                    trim(split_part(name, ' ', 1))
                ELSE 'Unknown'
            END,
            last_name = CASE 
                WHEN surname IS NOT NULL AND trim(surname) != '' THEN 
                    trim(surname)
                WHEN name IS NOT NULL AND trim(name) != '' AND position(' ' in name) > 0 THEN 
                    trim(split_part(name, ' ', array_length(string_to_array(name, ' '), 1)))
                ELSE 'Unknown'
            END
        WHERE first_name IS NULL OR last_name IS NULL
    """))
    
    # Now make first_name and last_name NOT NULL
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('first_name', nullable=False)
        batch_op.alter_column('last_name', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('middle_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
