"""Add status column to students table

Revision ID: 16ba5c78fa62
Revises: 0a6b8fac5558
Create Date: 2025-06-22 22:21:53.751372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ba5c78fa62'
down_revision = '0a6b8fac5558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
