"""add_parent_child_setup_delegate

Revision ID: 171c6e2c9ef4
Revises: 20260526_schema_drift_repair_001
Create Date: 2026-05-26 22:55:26.306963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '171c6e2c9ef4'
down_revision = '20260526_schema_drift_repair_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    table_exists = False
    if bind.dialect.name == 'postgresql':
        result = bind.execute(sa.text("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = 'parent_child_setup_tasks'
        """))
        table_exists = result.scalar() > 0
    else:
        try:
            bind.execute(sa.text("SELECT 1 FROM parent_child_setup_tasks LIMIT 1"))
            table_exists = True
        except Exception:
            table_exists = False

    if not table_exists:
        op.create_table('parent_child_setup_tasks',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.UUID(), nullable=False),
            sa.Column('parent_id', sa.Integer(), nullable=False),
            sa.Column('student_id', sa.Integer(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('task_type', sa.String(length=50), nullable=True),
            sa.Column('title', sa.String(length=255), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
            sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_parent_child_setup_tasks_tenant_id'), 'parent_child_setup_tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    table_exists = False
    if bind.dialect.name == 'postgresql':
        result = bind.execute(sa.text("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = 'parent_child_setup_tasks'
        """))
        table_exists = result.scalar() > 0
    else:
        try:
            bind.execute(sa.text("SELECT 1 FROM parent_child_setup_tasks LIMIT 1"))
            table_exists = True
        except Exception:
            table_exists = False

    if table_exists:
        op.drop_index(op.f('ix_parent_child_setup_tasks_tenant_id'), table_name='parent_child_setup_tasks')
        op.drop_table('parent_child_setup_tasks')
    # ### end Alembic commands ###
