"""Enhance_models

Revision ID: 3e1e9a4c3fff
Revises: bf57955d08a9
Create Date: 2026-02-19 00:40:27.878230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e1e9a4c3fff'
down_revision = 'bf57955d08a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE enhanced_grades DROP CONSTRAINT IF EXISTS enhanced_grades_assessment_type_id_fkey')
    
    # Drop constraints for tables that will be dropped or modified
    op.drop_constraint('competency_indicators_domain_id_fkey', 'competency_indicators', type_='foreignkey')
    op.drop_constraint('competency_indicators_proficiency_level_id_fkey', 'competency_indicators', type_='foreignkey')
    op.drop_constraint('character_traits_domain_id_fkey', 'character_traits', type_='foreignkey')
    op.drop_constraint('grading_schemes_grading_standard_id_fkey', 'grading_schemes', type_='foreignkey')

    op.drop_table('assessment_types')

    op.drop_table('assessment_modes')
    op.drop_table('differentiation_strategies')
    op.drop_table('competency_domains')
    op.drop_table('country_configs')
    op.drop_table('fee_payments')
    op.drop_table('grading_schemes_saas')
    op.drop_table('assessment_frequencies')
    op.drop_table('grading_standards')
    op.drop_table('campuses')
    op.drop_table('character_domains')
    op.drop_table('fee_records')
    op.drop_table('proficiency_levels')
    op.drop_table('supported_languages')
    op.drop_index(op.f('idx_announcements_class_id'), table_name='announcements')
    op.drop_index(op.f('idx_announcements_teacher_id'), table_name='announcements')
    op.alter_column('assessment_frameworks', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assessment_frameworks', 'formative_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'summative_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'school_based_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'project_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'formative_frequency',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'summative_frequency',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'curriculum_standards',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='curriculum_standards::json')
    op.alter_column('assessment_frameworks', 'competency_indicators',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='competency_indicators::json')
    op.drop_index(op.f('idx_assessment_frameworks_level_subject'), table_name='assessment_frameworks')
    op.drop_column('assessment_frameworks', 'assessment_criteria')
    op.drop_column('assessment_frameworks', 'is_active')
    op.drop_column('assessment_frameworks', 'framework_type')
    op.drop_column('assessment_frameworks', 'scoring_rubric')
    op.drop_index(op.f('idx_assignment_submissions_assignment_id'), table_name='assignment_submissions')
    op.drop_index(op.f('idx_assignment_submissions_graded_by'), table_name='assignment_submissions')
    op.drop_index(op.f('idx_assignment_submissions_status'), table_name='assignment_submissions')
    op.drop_index(op.f('idx_assignment_submissions_student_id'), table_name='assignment_submissions')
    op.drop_index(op.f('idx_assignment_submissions_submission_date'), table_name='assignment_submissions')
    op.drop_index(op.f('idx_assignments_assignment_type'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_class_id'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_due_date'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_status'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_subject_id'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_teacher_id'), table_name='assignments')
    op.drop_constraint(op.f('assignments_class_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'classes', ['class_id'], ['id'])
    op.alter_column('attendances', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_attendances_class_date'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_class_id'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_date'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_date_status'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_recorded_by'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_status'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_student_date'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_student_id'), table_name='attendances')
    op.drop_index(op.f('idx_attendances_subject_id'), table_name='attendances')
    op.create_index(op.f('ix_attendances_class_id'), 'attendances', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_student_id'), 'attendances', ['student_id'], unique=False)
    op.drop_index(op.f('idx_books_author'), table_name='books')
    op.drop_index(op.f('idx_books_category'), table_name='books')
    op.drop_index(op.f('idx_books_isbn'), table_name='books')
    op.drop_index(op.f('idx_books_status'), table_name='books')
    op.drop_index(op.f('idx_books_title'), table_name='books')
    op.drop_index(op.f('idx_borrow_records_book_id'), table_name='borrow_records')
    op.drop_index(op.f('idx_borrow_records_due_date'), table_name='borrow_records')
    op.drop_index(op.f('idx_borrow_records_member_id'), table_name='borrow_records')
    op.drop_index(op.f('idx_borrow_records_return_date'), table_name='borrow_records')
    op.drop_index(op.f('idx_borrow_records_status'), table_name='borrow_records')
    op.add_column('character_traits', sa.Column('domain', sa.Enum('RELIGIOUS_VALUES', 'MORAL_VALUES', 'CULTURAL_VALUES', 'CIVIC_VALUES', 'SOCIAL_VALUES', 'PERSONAL_VALUES', name='characterdomain'), nullable=False))
    op.alter_column('character_traits', 'educational_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_character_traits_level_domain'), table_name='character_traits')
    op.drop_column('character_traits', 'domain_id')
    op.drop_column('character_traits', 'is_active')
    op.drop_index(op.f('idx_class_subjects_class_id'), table_name='class_subjects')
    op.drop_index(op.f('idx_class_subjects_subject_id'), table_name='class_subjects')
    op.drop_constraint(op.f('class_subjects_class_id_fkey'), 'class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_subjects', 'classes', ['class_id'], ['id'])
    op.alter_column('classes', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_classes_academic_year'), table_name='classes')
    op.drop_index(op.f('idx_classes_created_at'), table_name='classes')
    op.drop_index(op.f('idx_classes_educational_level_id'), table_name='classes')
    op.drop_index(op.f('idx_classes_grade_level'), table_name='classes')
    op.drop_index(op.f('idx_classes_status'), table_name='classes')
    op.drop_index(op.f('idx_classes_teacher_id'), table_name='classes')
    op.add_column('competency_indicators', sa.Column('competency_id', sa.Integer(), nullable=False))
    op.add_column('competency_indicators', sa.Column('indicator_text', sa.Text(), nullable=False))
    op.add_column('competency_indicators', sa.Column('domain', sa.Enum('COMMUNICATION_COLLABORATION', 'CRITICAL_THINKING_PROBLEM_SOLVING', 'CREATIVITY_INNOVATION', 'CULTURAL_IDENTITY_GLOBAL_CITIZENSHIP', 'PERSONAL_DEVELOPMENT_LEADERSHIP', 'DIGITAL_LITERACY', name='competencydomain'), nullable=False))
    op.add_column('competency_indicators', sa.Column('min_educational_level', sa.Integer(), nullable=False))
    op.add_column('competency_indicators', sa.Column('max_educational_level', sa.Integer(), nullable=False))
    op.add_column('competency_indicators', sa.Column('is_observable', sa.Boolean(), nullable=True))
    op.add_column('competency_indicators', sa.Column('assessment_methods', sa.JSON(), nullable=True))
    op.add_column('competency_indicators', sa.Column('level_1_descriptor', sa.Text(), nullable=True))
    op.add_column('competency_indicators', sa.Column('level_2_descriptor', sa.Text(), nullable=True))
    op.add_column('competency_indicators', sa.Column('level_3_descriptor', sa.Text(), nullable=True))
    op.add_column('competency_indicators', sa.Column('level_4_descriptor', sa.Text(), nullable=True))
    op.drop_constraint(op.f('competency_indicators_educational_level_id_fkey'), 'competency_indicators', type_='foreignkey')
    op.create_foreign_key(None, 'competency_indicators', 'core_competencies', ['competency_id'], ['id'])
    op.drop_column('competency_indicators', 'domain_id')
    op.drop_column('competency_indicators', 'educational_level_id')
    op.drop_column('competency_indicators', 'proficiency_level_id')
    op.drop_column('competency_indicators', 'description')
    op.alter_column('continuous_assessment_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_continuous_assessment_academic_year_term'), table_name='continuous_assessment_records')
    op.drop_index(op.f('idx_continuous_assessment_class_id'), table_name='continuous_assessment_records')
    op.drop_index(op.f('idx_continuous_assessment_student_id'), table_name='continuous_assessment_records')
    op.drop_index(op.f('idx_continuous_assessment_subject_id'), table_name='continuous_assessment_records')
    op.alter_column('curricula', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('curricula', 'educational_level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('curricula', 'curriculum_standard', server_default=None, existing_type=sa.VARCHAR(length=50))
    op.alter_column('curricula', 'curriculum_standard',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.Enum('STANDARDS_BASED', 'COMPETENCY_BASED', 'STEM_FOCUSED', 'CHARACTER_DEVELOPMENT', name='curriculumstandard'),
               nullable=False,
               postgresql_using="upper(curriculum_standard)::curriculumstandard")
    op.alter_column('curricula', 'term',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('curricula', 'duration_weeks',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('curricula', 'critical_thinking_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('curricula', 'creativity_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('curricula', 'communication_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('curricula', 'collaboration_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('curricula', 'sba_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('curricula', 'external_exam_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.create_foreign_key(None, 'curricula', 'users', ['approved_by'], ['id'])
    op.drop_column('curricula', 'grade_level')
    op.drop_constraint(op.f('educational_levels_name_key'), 'educational_levels', type_='unique')
    op.alter_column('educational_system_config', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('educational_system_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('educational_system_templates', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('educational_system_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('educational_system_templates', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('enhanced_grades', 'term',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('enhanced_grades', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('enhanced_grades', 'total_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('enhanced_grades', 'percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('idx_enhanced_grades_student_subject'), table_name='enhanced_grades')
    op.drop_constraint(op.f('fk_enhanced_grades_class_id'), 'enhanced_grades', type_='foreignkey')
    op.drop_constraint(op.f('enhanced_grades_teacher_id_fkey'), 'enhanced_grades', type_='foreignkey')
    # op.drop_constraint(op.f('enhanced_grades_assessment_type_id_fkey'), 'enhanced_grades', type_='foreignkey')
    op.drop_constraint(op.f('enhanced_grades_student_id_fkey'), 'enhanced_grades', type_='foreignkey')
    op.create_foreign_key(None, 'enhanced_grades', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(None, 'enhanced_grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('enhanced_grades', 'weighted_score')
    op.drop_column('enhanced_grades', 'grade_point')
    op.drop_column('enhanced_grades', 'updated_at')
    op.drop_column('enhanced_grades', 'teacher_id')
    op.drop_column('enhanced_grades', 'created_at')
    op.drop_column('enhanced_grades', 'grade')
    op.drop_index(op.f('idx_exams_class_date'), table_name='exams')
    op.drop_index(op.f('idx_exams_class_id'), table_name='exams')
    op.drop_index(op.f('idx_exams_created_at'), table_name='exams')
    op.drop_index(op.f('idx_exams_created_by'), table_name='exams')
    op.drop_index(op.f('idx_exams_date_status'), table_name='exams')
    op.drop_index(op.f('idx_exams_exam_date'), table_name='exams')
    op.drop_index(op.f('idx_exams_status'), table_name='exams')
    op.drop_index(op.f('idx_exams_subject_id'), table_name='exams')
    op.drop_constraint(op.f('exams_class_id_fkey'), 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'classes', ['class_id'], ['id'])
    op.add_column('fee_structures', sa.Column('fee_category_id', sa.Integer(), nullable=False))
    op.add_column('fee_structures', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('fee_structures', sa.Column('educational_level_id', sa.Integer(), nullable=True))
    op.add_column('fee_structures', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('fee_structures', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('fee_structures', sa.Column('due_date', sa.Date(), nullable=True))
    op.alter_column('fee_structures', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_fee_structures_academic_year'), table_name='fee_structures')
    op.drop_index(op.f('idx_fee_structures_grade_level'), table_name='fee_structures')
    op.drop_index(op.f('idx_fee_structures_is_active'), table_name='fee_structures')
    op.drop_index(op.f('idx_fee_structures_term'), table_name='fee_structures')
    op.drop_constraint(op.f('fee_structures_created_by_fkey'), 'fee_structures', type_='foreignkey')
    op.create_foreign_key(None, 'fee_structures', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(None, 'fee_structures', 'educational_levels', ['educational_level_id'], ['id'])
    op.create_foreign_key(None, 'fee_structures', 'fee_categories', ['fee_category_id'], ['id'])
    op.drop_column('fee_structures', 'grade_level')
    op.drop_column('fee_structures', 'created_by')
    op.drop_column('fee_structures', 'uniform_fee')
    op.drop_column('fee_structures', 'laboratory_fee')
    op.drop_column('fee_structures', 'library_fee')
    op.drop_column('fee_structures', 'name')
    op.drop_column('fee_structures', 'registration_fee')
    op.drop_column('fee_structures', 'transport_fee')
    op.drop_column('fee_structures', 'sports_fee')
    op.drop_column('fee_structures', 'updated_at')
    op.drop_column('fee_structures', 'tuition_fee')
    op.drop_column('fee_structures', 'examination_fee')
    op.drop_column('fee_structures', 'total_fee')
    op.drop_column('fee_structures', 'is_active')
    op.drop_column('fee_structures', 'miscellaneous_fee')
    op.alter_column('final_grades', 'academic_year',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('final_grades', 'final_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('final_grades', 'final_grade_symbol',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('final_grades', 'is_passing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('final_grades', 'computed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_final_grades_student_term'), table_name='final_grades')
    op.drop_constraint(op.f('fk_final_grades_computed_by'), 'final_grades', type_='foreignkey')
    op.drop_constraint(op.f('final_grades_student_id_fkey'), 'final_grades', type_='foreignkey')
    op.create_foreign_key(None, 'final_grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'final_grades', 'users', ['computed_by'], ['id'])
    op.drop_column('final_grades', 'updated_at')
    op.drop_column('final_grades', 'created_at')
    op.add_column('grade_boundaries', sa.Column('grade_symbol', sa.String(length=5), nullable=False))
    op.add_column('grade_boundaries', sa.Column('grade_name', sa.String(length=50), nullable=True))
    op.add_column('grade_boundaries', sa.Column('is_passing', sa.Boolean(), nullable=True))
    op.add_column('grade_boundaries', sa.Column('grade_points', sa.Float(), nullable=True))
    op.add_column('grade_boundaries', sa.Column('sequence_order', sa.Integer(), nullable=False))
    op.add_column('grade_boundaries', sa.Column('color_code', sa.String(length=7), nullable=True))
    op.drop_column('grade_boundaries', 'grade_point')
    op.drop_column('grade_boundaries', 'interpretation')
    op.drop_column('grade_boundaries', 'updated_at')
    op.drop_column('grade_boundaries', 'created_at')
    op.drop_column('grade_boundaries', 'grade')
    op.alter_column('grade_levels', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('grade_levels', 'is_terminal',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_grades_academic_year'), table_name='grades')
    op.drop_index(op.f('idx_grades_assessment_type'), table_name='grades')
    op.drop_index(op.f('idx_grades_class_id'), table_name='grades')
    op.drop_index(op.f('idx_grades_class_subject_term'), table_name='grades')
    op.drop_index(op.f('idx_grades_created_at'), table_name='grades')
    op.drop_index(op.f('idx_grades_exam_id'), table_name='grades')
    op.drop_index(op.f('idx_grades_graded_by'), table_name='grades')
    op.drop_index(op.f('idx_grades_is_final'), table_name='grades')
    op.drop_index(op.f('idx_grades_student_id'), table_name='grades')
    op.drop_index(op.f('idx_grades_student_term_year'), table_name='grades')
    op.drop_index(op.f('idx_grades_subject_id'), table_name='grades')
    op.drop_index(op.f('idx_grades_term'), table_name='grades')
    op.create_index(op.f('ix_grades_class_id'), 'grades', ['class_id'], unique=False)
    op.create_index(op.f('ix_grades_subject_id'), 'grades', ['subject_id'], unique=False)
    op.drop_constraint(op.f('fk_grades_class_id'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'classes', ['class_id'], ['id'])
    op.add_column('grading_schemes', sa.Column('standard', sa.Enum('CONTINUOUS_ASSESSMENT', 'BECE', 'WASSCE', 'INTERNAL_EXAM', name='gradingstandard'), nullable=False))
    op.add_column('grading_schemes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('grading_schemes', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('grading_schemes', sa.Column('class_score_weight', sa.Float(), nullable=True))
    op.add_column('grading_schemes', sa.Column('external_exam_weight', sa.Float(), nullable=True))
    op.drop_constraint(op.f('grading_schemes_subject_id_fkey'), 'grading_schemes', type_='foreignkey')
    op.drop_column('grading_schemes', 'grading_standard_id')
    op.drop_column('grading_schemes', 'subject_id')
    op.add_column('learning_approaches', sa.Column('code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'learning_approaches', ['code'])
    op.drop_column('learning_approaches', 'methodology')
    op.drop_index(op.f('idx_library_members_is_active'), table_name='library_members')
    op.drop_index(op.f('idx_library_members_member_id'), table_name='library_members')
    op.drop_index(op.f('idx_library_members_user_id'), table_name='library_members')
    op.drop_index(op.f('idx_login_history_ip_address'), table_name='login_history')
    op.drop_index(op.f('idx_login_history_login_timestamp'), table_name='login_history')
    op.drop_index(op.f('idx_login_history_success'), table_name='login_history')
    op.drop_index(op.f('idx_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_is_read'), table_name='messages')
    op.drop_index(op.f('idx_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_recipient_read'), table_name='messages')
    op.drop_index(op.f('idx_messages_recipient_type'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender_created'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender_type'), table_name='messages')
    op.alter_column('notifications', 'id',
               existing_type=sa.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_time'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_type'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_time'), table_name='notifications')
    op.drop_index(op.f('idx_parents_user_id'), table_name='parents')
    op.alter_column('platform_audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('platform_audit_log_tenant_id_fkey'), 'platform_audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'platform_audit_log', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('school_based_assessments', 'class_exercises_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'homework_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'project_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'assignment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'class_test_average',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'total_sba_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'sba_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_sba_academic_year_term'), table_name='school_based_assessments')
    op.drop_index(op.f('idx_sba_class_id'), table_name='school_based_assessments')
    op.drop_index(op.f('idx_sba_student_id'), table_name='school_based_assessments')
    op.drop_index(op.f('idx_sba_subject_id'), table_name='school_based_assessments')
    op.drop_index(op.f('idx_sba_teacher_id'), table_name='school_based_assessments')
    op.drop_index(op.f('idx_stem_assessment_results_student'), table_name='stem_assessment_results')
    op.drop_index(op.f('idx_stem_assessments_module'), table_name='stem_assessments')
    op.add_column('stem_learning_modules', sa.Column('primary_approach_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_stem_learning_modules_subject_level'), table_name='stem_learning_modules')
    op.create_foreign_key(None, 'stem_learning_modules', 'learning_approaches', ['primary_approach_id'], ['id'])
    op.drop_column('stem_learning_modules', 'primary_approach')
    op.drop_index(op.f('idx_stem_projects_module'), table_name='stem_projects')
    op.drop_index(op.f('idx_stem_resource_bookings_class'), table_name='stem_resource_bookings')
    op.drop_index(op.f('idx_stem_resource_bookings_date'), table_name='stem_resource_bookings')
    op.drop_constraint(op.f('stem_resource_bookings_class_id_fkey'), 'stem_resource_bookings', type_='foreignkey')
    op.create_foreign_key(None, 'stem_resource_bookings', 'classes', ['class_id'], ['id'])
    op.alter_column('student_competency_assessments', 'term',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('student_competency_assessments', 'academic_year',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('student_competency_assessments', 'level_achieved',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_competency_assessments', 'assessed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_student_competency_student_id'), table_name='student_competency_assessments')
    op.drop_constraint(op.f('student_competency_assessments_student_id_fkey'), 'student_competency_assessments', type_='foreignkey')
    op.drop_constraint(op.f('student_competency_assessments_teacher_id_fkey'), 'student_competency_assessments', type_='foreignkey')
    op.create_foreign_key(None, 'student_competency_assessments', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('student_competency_assessments', 'score')
    op.drop_column('student_competency_assessments', 'proficiency_level')
    op.drop_column('student_competency_assessments', 'teacher_id')
    op.alter_column('students', 'individualized_education_plan',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_students_admission_number'), table_name='students')
    op.drop_index(op.f('idx_students_class_id'), table_name='students')
    op.drop_index(op.f('idx_students_created_at'), table_name='students')
    op.drop_index(op.f('idx_students_date_of_birth'), table_name='students')
    op.drop_index(op.f('idx_students_first_name'), table_name='students')
    op.drop_index(op.f('idx_students_gender'), table_name='students')
    op.drop_index(op.f('idx_students_last_name'), table_name='students')
    op.drop_index(op.f('idx_students_parent_id'), table_name='students')
    op.drop_index(op.f('idx_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.drop_constraint(op.f('students_class_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['id'])
    op.alter_column('subscriptions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('idx_teacher_subjects_subject_id'), table_name='teacher_subjects')
    op.drop_index(op.f('idx_teacher_subjects_teacher_id'), table_name='teacher_subjects')
    op.drop_index(op.f('idx_teachers_created_at'), table_name='teachers')
    op.drop_index(op.f('idx_teachers_employee_id'), table_name='teachers')
    op.drop_index(op.f('idx_teachers_first_name'), table_name='teachers')
    op.drop_index(op.f('idx_teachers_last_name'), table_name='teachers')
    op.drop_index(op.f('idx_teachers_status'), table_name='teachers')
    op.drop_index(op.f('idx_teachers_user_id'), table_name='teachers')
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'enabled_features',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tenants', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_transactions_created_by'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_reference_number'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('idx_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('idx_user_roles_user_id'), table_name='user_roles')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('mfa_backup_codes', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('mfa_temp_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_temp_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('trusted_device_list', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('security_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('login_notifications', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_last_login'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'login_notifications')
    op.drop_column('users', 'security_notifications')
    op.drop_column('users', 'trusted_device_list')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'mfa_temp_token_expires')
    op.drop_column('users', 'mfa_temp_token')
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verified')
    op.create_index(op.f('idx_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('idx_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('idx_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('idx_transactions_reference_number'), 'transactions', ['reference_number'], unique=False)
    op.create_index(op.f('idx_transactions_created_by'), 'transactions', ['created_by'], unique=False)
    op.alter_column('tenants', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=True)
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=True)
    op.alter_column('tenants', 'default_language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=True)
    op.alter_column('tenants', 'enabled_features',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=True)
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'trial'::character varying"),
               existing_nullable=True)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'trial'::character varying"),
               existing_nullable=True)
    op.alter_column('tenants', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_teachers_user_id'), 'teachers', ['user_id'], unique=False)
    op.create_index(op.f('idx_teachers_status'), 'teachers', ['status'], unique=False)
    op.create_index(op.f('idx_teachers_last_name'), 'teachers', ['last_name'], unique=False)
    op.create_index(op.f('idx_teachers_first_name'), 'teachers', ['first_name'], unique=False)
    op.create_index(op.f('idx_teachers_employee_id'), 'teachers', ['employee_id'], unique=False)
    op.create_index(op.f('idx_teachers_created_at'), 'teachers', ['created_at'], unique=False)
    op.create_index(op.f('idx_teacher_subjects_teacher_id'), 'teacher_subjects', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_teacher_subjects_subject_id'), 'teacher_subjects', ['subject_id'], unique=False)
    op.drop_constraint(None, 'subscriptions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_class_id_fkey'), 'students', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_students_parent_id'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.create_index(op.f('idx_students_user_id'), 'students', ['user_id'], unique=False)
    op.create_index(op.f('idx_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.create_index(op.f('idx_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('idx_students_gender'), 'students', ['gender'], unique=False)
    op.create_index(op.f('idx_students_first_name'), 'students', ['first_name'], unique=False)
    op.create_index(op.f('idx_students_date_of_birth'), 'students', ['date_of_birth'], unique=False)
    op.create_index(op.f('idx_students_created_at'), 'students', ['created_at'], unique=False)
    op.create_index(op.f('idx_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('idx_students_admission_number'), 'students', ['admission_number'], unique=False)
    op.alter_column('students', 'individualized_education_plan',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.add_column('student_competency_assessments', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_competency_assessments', sa.Column('proficiency_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('student_competency_assessments', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_competency_assessments', type_='foreignkey')
    op.create_foreign_key(op.f('student_competency_assessments_teacher_id_fkey'), 'student_competency_assessments', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('student_competency_assessments_student_id_fkey'), 'student_competency_assessments', 'students', ['student_id'], ['id'])
    op.create_index(op.f('idx_student_competency_student_id'), 'student_competency_assessments', ['student_id'], unique=False)
    op.alter_column('student_competency_assessments', 'assessed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_competency_assessments', 'level_achieved',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_competency_assessments', 'academic_year',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('student_competency_assessments', 'term',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'stem_resource_bookings', type_='foreignkey')
    op.create_foreign_key(op.f('stem_resource_bookings_class_id_fkey'), 'stem_resource_bookings', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_stem_resource_bookings_date'), 'stem_resource_bookings', ['booking_date', 'resource_id'], unique=False)
    op.create_index(op.f('idx_stem_resource_bookings_class'), 'stem_resource_bookings', ['class_id'], unique=False)
    op.create_index(op.f('idx_stem_projects_module'), 'stem_projects', ['learning_module_id'], unique=False)
    op.add_column('stem_learning_modules', sa.Column('primary_approach', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stem_learning_modules', type_='foreignkey')
    op.create_index(op.f('idx_stem_learning_modules_subject_level'), 'stem_learning_modules', ['stem_subject_id', 'educational_level_id'], unique=False)
    op.drop_column('stem_learning_modules', 'primary_approach_id')
    op.create_index(op.f('idx_stem_assessments_module'), 'stem_assessments', ['learning_module_id'], unique=False)
    op.create_index(op.f('idx_stem_assessment_results_student'), 'stem_assessment_results', ['student_id', 'assessment_id'], unique=False)
    op.create_index(op.f('idx_sba_teacher_id'), 'school_based_assessments', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_sba_subject_id'), 'school_based_assessments', ['subject_id'], unique=False)
    op.create_index(op.f('idx_sba_student_id'), 'school_based_assessments', ['student_id'], unique=False)
    op.create_index(op.f('idx_sba_class_id'), 'school_based_assessments', ['class_id'], unique=False)
    op.create_index(op.f('idx_sba_academic_year_term'), 'school_based_assessments', ['academic_year', 'term'], unique=False)
    op.alter_column('school_based_assessments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'is_moderated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'sba_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'total_sba_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'class_test_average',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'assignment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'project_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'homework_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('school_based_assessments', 'class_exercises_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.drop_constraint(None, 'platform_audit_log', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('platform_audit_log_tenant_id_fkey'), 'platform_audit_log', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('platform_audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('idx_parents_user_id'), 'parents', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_user_time'), 'notifications', ['user_id', 'time'], unique=False)
    op.create_index(op.f('idx_notifications_user_read'), 'notifications', ['user_id', 'read'], unique=False)
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('idx_notifications_time'), 'notifications', ['time'], unique=False)
    op.create_index(op.f('idx_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text("nextval('notifications_id_seq'::regclass)"),
               existing_nullable=False)
    op.create_index(op.f('idx_messages_sender_type'), 'messages', ['sender_type'], unique=False)
    op.create_index(op.f('idx_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_messages_sender_created'), 'messages', ['sender_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_messages_recipient_type'), 'messages', ['recipient_type'], unique=False)
    op.create_index(op.f('idx_messages_recipient_read'), 'messages', ['recipient_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('idx_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_login_history_success'), 'login_history', ['success'], unique=False)
    op.create_index(op.f('idx_login_history_login_timestamp'), 'login_history', ['login_timestamp'], unique=False)
    op.create_index(op.f('idx_login_history_ip_address'), 'login_history', ['ip_address'], unique=False)
    op.create_index(op.f('idx_library_members_user_id'), 'library_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_library_members_member_id'), 'library_members', ['member_id'], unique=False)
    op.create_index(op.f('idx_library_members_is_active'), 'library_members', ['is_active'], unique=False)
    op.add_column('learning_approaches', sa.Column('methodology', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'learning_approaches', type_='unique')
    op.drop_column('learning_approaches', 'code')
    op.add_column('grading_schemes', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grading_schemes', sa.Column('grading_standard_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('grading_schemes_grading_standard_id_fkey'), 'grading_schemes', 'grading_standards', ['grading_standard_id'], ['id'])
    op.create_foreign_key(op.f('grading_schemes_subject_id_fkey'), 'grading_schemes', 'subjects', ['subject_id'], ['id'])
    op.drop_column('grading_schemes', 'external_exam_weight')
    op.drop_column('grading_schemes', 'class_score_weight')
    op.drop_column('grading_schemes', 'is_default')
    op.drop_column('grading_schemes', 'description')
    op.drop_column('grading_schemes', 'standard')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('fk_grades_class_id'), 'grades', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_grades_subject_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_class_id'), table_name='grades')
    op.create_index(op.f('idx_grades_term'), 'grades', ['term'], unique=False)
    op.create_index(op.f('idx_grades_subject_id'), 'grades', ['subject_id'], unique=False)
    op.create_index(op.f('idx_grades_student_term_year'), 'grades', ['student_id', 'term', 'academic_year'], unique=False)
    op.create_index(op.f('idx_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_index(op.f('idx_grades_is_final'), 'grades', ['is_final'], unique=False)
    op.create_index(op.f('idx_grades_graded_by'), 'grades', ['graded_by'], unique=False)
    op.create_index(op.f('idx_grades_exam_id'), 'grades', ['exam_id'], unique=False)
    op.create_index(op.f('idx_grades_created_at'), 'grades', ['created_at'], unique=False)
    op.create_index(op.f('idx_grades_class_subject_term'), 'grades', ['class_id', 'subject_id', 'term'], unique=False)
    op.create_index(op.f('idx_grades_class_id'), 'grades', ['class_id'], unique=False)
    op.create_index(op.f('idx_grades_assessment_type'), 'grades', ['assessment_type'], unique=False)
    op.create_index(op.f('idx_grades_academic_year'), 'grades', ['academic_year'], unique=False)
    op.alter_column('grade_levels', 'is_terminal',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('grade_levels', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('grade_boundaries', sa.Column('grade', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('grade_boundaries', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('grade_boundaries', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('grade_boundaries', sa.Column('interpretation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('grade_boundaries', sa.Column('grade_point', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('grade_boundaries', 'color_code')
    op.drop_column('grade_boundaries', 'sequence_order')
    op.drop_column('grade_boundaries', 'grade_points')
    op.drop_column('grade_boundaries', 'is_passing')
    op.drop_column('grade_boundaries', 'grade_name')
    op.drop_column('grade_boundaries', 'grade_symbol')
    op.add_column('final_grades', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('final_grades', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'final_grades', type_='foreignkey')
    op.drop_constraint(None, 'final_grades', type_='foreignkey')
    op.create_foreign_key(op.f('final_grades_student_id_fkey'), 'final_grades', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('fk_final_grades_computed_by'), 'final_grades', 'users', ['computed_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_final_grades_student_term'), 'final_grades', ['student_id', 'term', 'academic_year'], unique=False)
    op.alter_column('final_grades', 'computed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('final_grades', 'is_passing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('final_grades', 'final_grade_symbol',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('final_grades', 'final_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('final_grades', 'academic_year',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.add_column('fee_structures', sa.Column('miscellaneous_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('total_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('fee_structures', sa.Column('examination_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('tuition_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('sports_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('transport_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('registration_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('fee_structures', sa.Column('library_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('laboratory_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('uniform_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fee_structures', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fee_structures', sa.Column('grade_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fee_structures', type_='foreignkey')
    op.drop_constraint(None, 'fee_structures', type_='foreignkey')
    op.drop_constraint(None, 'fee_structures', type_='foreignkey')
    op.create_foreign_key(op.f('fee_structures_created_by_fkey'), 'fee_structures', 'users', ['created_by'], ['id'])
    op.create_index(op.f('idx_fee_structures_term'), 'fee_structures', ['term'], unique=False)
    op.create_index(op.f('idx_fee_structures_is_active'), 'fee_structures', ['is_active'], unique=False)
    op.create_index(op.f('idx_fee_structures_grade_level'), 'fee_structures', ['grade_level'], unique=False)
    op.create_index(op.f('idx_fee_structures_academic_year'), 'fee_structures', ['academic_year'], unique=False)
    op.alter_column('fee_structures', 'academic_year',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('fee_structures', 'due_date')
    op.drop_column('fee_structures', 'currency')
    op.drop_column('fee_structures', 'amount')
    op.drop_column('fee_structures', 'educational_level_id')
    op.drop_column('fee_structures', 'class_id')
    op.drop_column('fee_structures', 'fee_category_id')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key(op.f('exams_class_id_fkey'), 'exams', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_index(op.f('idx_exams_status'), 'exams', ['status'], unique=False)
    op.create_index(op.f('idx_exams_exam_date'), 'exams', ['exam_date'], unique=False)
    op.create_index(op.f('idx_exams_date_status'), 'exams', ['exam_date', 'status'], unique=False)
    op.create_index(op.f('idx_exams_created_by'), 'exams', ['created_by'], unique=False)
    op.create_index(op.f('idx_exams_created_at'), 'exams', ['created_at'], unique=False)
    op.create_index(op.f('idx_exams_class_id'), 'exams', ['class_id'], unique=False)
    op.create_index(op.f('idx_exams_class_date'), 'exams', ['class_id', 'exam_date'], unique=False)
    op.add_column('enhanced_grades', sa.Column('grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('enhanced_grades', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('enhanced_grades', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enhanced_grades', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('enhanced_grades', sa.Column('grade_point', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('enhanced_grades', sa.Column('weighted_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enhanced_grades', type_='foreignkey')
    op.drop_constraint(None, 'enhanced_grades', type_='foreignkey')
    op.create_foreign_key(op.f('enhanced_grades_student_id_fkey'), 'enhanced_grades', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('enhanced_grades_assessment_type_id_fkey'), 'enhanced_grades', 'assessment_types', ['assessment_type_id'], ['id'])
    op.create_foreign_key(op.f('enhanced_grades_teacher_id_fkey'), 'enhanced_grades', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('fk_enhanced_grades_class_id'), 'enhanced_grades', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_enhanced_grades_student_subject'), 'enhanced_grades', ['student_id', 'subject_id'], unique=False)
    op.alter_column('enhanced_grades', 'percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('enhanced_grades', 'total_marks',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('enhanced_grades', 'academic_year',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('enhanced_grades', 'term',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('educational_system_templates', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('educational_system_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('educational_system_templates', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('educational_system_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('educational_system_config', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('educational_levels_name_key'), 'educational_levels', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('curricula', sa.Column('grade_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.alter_column('curricula', 'external_exam_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('60.0'),
               existing_nullable=True)
    op.alter_column('curricula', 'sba_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('40.0'),
               existing_nullable=True)
    op.alter_column('curricula', 'collaboration_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('25.0'),
               existing_nullable=True)
    op.alter_column('curricula', 'communication_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('25.0'),
               existing_nullable=True)
    op.alter_column('curricula', 'creativity_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('25.0'),
               existing_nullable=True)
    op.alter_column('curricula', 'critical_thinking_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('25.0'),
               existing_nullable=True)
    op.alter_column('curricula', 'duration_weeks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('13'),
               nullable=True)
    op.alter_column('curricula', 'term',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Term 1'::character varying"),
               nullable=True)
    op.alter_column('curricula', 'curriculum_standard',
               existing_type=sa.Enum('STANDARDS_BASED', 'COMPETENCY_BASED', 'STEM_FOCUSED', 'CHARACTER_DEVELOPMENT', name='curriculumstandard'),
               server_default=sa.text("'standards_based'::character varying"),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('curricula', 'educational_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('curricula', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_index(op.f('idx_continuous_assessment_subject_id'), 'continuous_assessment_records', ['subject_id'], unique=False)
    op.create_index(op.f('idx_continuous_assessment_student_id'), 'continuous_assessment_records', ['student_id'], unique=False)
    op.create_index(op.f('idx_continuous_assessment_class_id'), 'continuous_assessment_records', ['class_id'], unique=False)
    op.create_index(op.f('idx_continuous_assessment_academic_year_term'), 'continuous_assessment_records', ['academic_year', 'term'], unique=False)
    op.alter_column('continuous_assessment_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.add_column('competency_indicators', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('competency_indicators', sa.Column('proficiency_level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('competency_indicators', sa.Column('educational_level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('competency_indicators', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'competency_indicators', type_='foreignkey')
    op.create_foreign_key(op.f('competency_indicators_educational_level_id_fkey'), 'competency_indicators', 'educational_levels', ['educational_level_id'], ['id'])
    op.create_foreign_key(op.f('competency_indicators_proficiency_level_id_fkey'), 'competency_indicators', 'proficiency_levels', ['proficiency_level_id'], ['id'])
    op.create_foreign_key(op.f('competency_indicators_domain_id_fkey'), 'competency_indicators', 'competency_domains', ['domain_id'], ['id'])
    op.drop_column('competency_indicators', 'level_4_descriptor')
    op.drop_column('competency_indicators', 'level_3_descriptor')
    op.drop_column('competency_indicators', 'level_2_descriptor')
    op.drop_column('competency_indicators', 'level_1_descriptor')
    op.drop_column('competency_indicators', 'assessment_methods')
    op.drop_column('competency_indicators', 'is_observable')
    op.drop_column('competency_indicators', 'max_educational_level')
    op.drop_column('competency_indicators', 'min_educational_level')
    op.drop_column('competency_indicators', 'domain')
    op.drop_column('competency_indicators', 'indicator_text')
    op.drop_column('competency_indicators', 'competency_id')
    op.create_index(op.f('idx_classes_teacher_id'), 'classes', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_classes_status'), 'classes', ['status'], unique=False)
    op.create_index(op.f('idx_classes_grade_level'), 'classes', ['grade_level'], unique=False)
    op.create_index(op.f('idx_classes_educational_level_id'), 'classes', ['educational_level_id'], unique=False)
    op.create_index(op.f('idx_classes_created_at'), 'classes', ['created_at'], unique=False)
    op.create_index(op.f('idx_classes_academic_year'), 'classes', ['academic_year'], unique=False)
    op.alter_column('classes', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('class_subjects_class_id_fkey'), 'class_subjects', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_class_subjects_subject_id'), 'class_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('idx_class_subjects_class_id'), 'class_subjects', ['class_id'], unique=False)
    op.add_column('character_traits', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('character_traits', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('character_traits_domain_id_fkey'), 'character_traits', 'character_domains', ['domain_id'], ['id'])
    op.create_index(op.f('idx_character_traits_level_domain'), 'character_traits', ['educational_level_id', 'domain_id'], unique=False)
    op.alter_column('character_traits', 'educational_level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('character_traits', 'domain')
    op.create_index(op.f('idx_borrow_records_status'), 'borrow_records', ['status'], unique=False)
    op.create_index(op.f('idx_borrow_records_return_date'), 'borrow_records', ['return_date'], unique=False)
    op.create_index(op.f('idx_borrow_records_member_id'), 'borrow_records', ['member_id'], unique=False)
    op.create_index(op.f('idx_borrow_records_due_date'), 'borrow_records', ['due_date'], unique=False)
    op.create_index(op.f('idx_borrow_records_book_id'), 'borrow_records', ['book_id'], unique=False)
    op.create_index(op.f('idx_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('idx_books_status'), 'books', ['status'], unique=False)
    op.create_index(op.f('idx_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_index(op.f('idx_books_category'), 'books', ['category'], unique=False)
    op.create_index(op.f('idx_books_author'), 'books', ['author'], unique=False)
    op.drop_index(op.f('ix_attendances_student_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_class_id'), table_name='attendances')
    op.create_index(op.f('idx_attendances_subject_id'), 'attendances', ['subject_id'], unique=False)
    op.create_index(op.f('idx_attendances_student_id'), 'attendances', ['student_id'], unique=False)
    op.create_index(op.f('idx_attendances_student_date'), 'attendances', ['student_id', 'date'], unique=False)
    op.create_index(op.f('idx_attendances_status'), 'attendances', ['status'], unique=False)
    op.create_index(op.f('idx_attendances_recorded_by'), 'attendances', ['recorded_by'], unique=False)
    op.create_index(op.f('idx_attendances_date_status'), 'attendances', ['date', 'status'], unique=False)
    op.create_index(op.f('idx_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('idx_attendances_class_id'), 'attendances', ['class_id'], unique=False)
    op.create_index(op.f('idx_attendances_class_date'), 'attendances', ['class_id', 'date'], unique=False)
    op.alter_column('attendances', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_class_id_fkey'), 'assignments', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_assignments_teacher_id'), 'assignments', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_assignments_subject_id'), 'assignments', ['subject_id'], unique=False)
    op.create_index(op.f('idx_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('idx_assignments_due_date'), 'assignments', ['due_date'], unique=False)
    op.create_index(op.f('idx_assignments_class_id'), 'assignments', ['class_id'], unique=False)
    op.create_index(op.f('idx_assignments_assignment_type'), 'assignments', ['assignment_type'], unique=False)
    op.create_index(op.f('idx_assignment_submissions_submission_date'), 'assignment_submissions', ['submission_date'], unique=False)
    op.create_index(op.f('idx_assignment_submissions_student_id'), 'assignment_submissions', ['student_id'], unique=False)
    op.create_index(op.f('idx_assignment_submissions_status'), 'assignment_submissions', ['status'], unique=False)
    op.create_index(op.f('idx_assignment_submissions_graded_by'), 'assignment_submissions', ['graded_by'], unique=False)
    op.create_index(op.f('idx_assignment_submissions_assignment_id'), 'assignment_submissions', ['assignment_id'], unique=False)
    op.add_column('assessment_frameworks', sa.Column('scoring_rubric', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('assessment_frameworks', sa.Column('framework_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('assessment_frameworks', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('assessment_frameworks', sa.Column('assessment_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_assessment_frameworks_level_subject'), 'assessment_frameworks', ['educational_level_id', 'subject_id'], unique=False)
    op.alter_column('assessment_frameworks', 'competency_indicators',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'curriculum_standards',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'summative_frequency',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'termly'::character varying"),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'formative_frequency',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'weekly'::character varying"),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'project_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('10.0'),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'school_based_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('20.0'),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'summative_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('40.0'),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'formative_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('30.0'),
               existing_nullable=True)
    op.alter_column('assessment_frameworks', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_announcements_teacher_id'), 'announcements', ['teacher_id'], unique=False)
    op.create_index(op.f('idx_announcements_class_id'), 'announcements', ['class_id'], unique=False)
    op.create_table('supported_languages',
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name_native', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_rtl', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('tier', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('supported_languages_pkey'))
    )
    op.create_table('proficiency_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('proficiency_levels_pkey')),
    sa.UniqueConstraint('level_number', name=op.f('proficiency_levels_level_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('proficiency_levels_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('fee_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fee_structure_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_fee_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('paid_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('penalty_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='paymentstatus'), autoincrement=False, nullable=True),
    sa.Column('scholarship_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('scholarship_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fee_records_created_by_fkey')),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], name=op.f('fee_records_fee_structure_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fee_records_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_records_pkey'))
    )
    op.create_table('character_domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cultural_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('character_domains_pkey')),
    sa.UniqueConstraint('name', name=op.f('character_domains_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('campuses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_main_campus', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('campuses_pkey'))
    )
    op.create_table('grading_standards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('grading_standards_pkey')),
    sa.UniqueConstraint('code', name=op.f('grading_standards_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('grading_standards_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('assessment_frequencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('interval_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_frequencies_pkey')),
    sa.UniqueConstraint('name', name=op.f('assessment_frequencies_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('grading_schemes_saas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.NUMERIC(precision=6, scale=2), server_default=sa.text("'100'::numeric"), autoincrement=False, nullable=True),
    sa.Column('pass_mark', sa.NUMERIC(precision=6, scale=2), server_default=sa.text("'50'::numeric"), autoincrement=False, nullable=True),
    sa.Column('scale', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('grading_schemes_saas_pkey'))
    )
    op.create_table('fee_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fee_record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('receipt_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cheque_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mobile_money_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fee_record_id'], ['fee_records.id'], name=op.f('fee_payments_fee_record_id_fkey')),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fee_payments_processed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_payments_pkey')),
    sa.UniqueConstraint('receipt_number', name=op.f('fee_payments_receipt_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('reference_number', name=op.f('fee_payments_reference_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('country_configs',
    sa.Column('code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('currency_symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('phone_prefix', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('default_timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_rtl', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('supported_payment_gateways', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('supported_sms_providers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('country_configs_pkey'))
    )
    op.create_table('competency_domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('competency_domains_pkey')),
    sa.UniqueConstraint('name', name=op.f('competency_domains_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('differentiation_strategies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('implementation_guide', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('target_learning_styles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('differentiation_strategies_pkey')),
    sa.UniqueConstraint('name', name=op.f('differentiation_strategies_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('assessment_modes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_digital', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requires_supervision', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_modes_pkey')),
    sa.UniqueConstraint('code', name=op.f('assessment_modes_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('assessment_modes_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('assessment_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('weight_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_types_pkey')),
    sa.UniqueConstraint('code', name=op.f('assessment_types_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('assessment_types_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
