"""Add user_roles association table

Revision ID: 913618fd2a51
Revises: c538ebc90c70
Create Date: 2025-06-21 00:33:59.147656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913618fd2a51'
down_revision = 'c538ebc90c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    # ### end Alembic commands ###
