"""Add new fields to Class model

Revision ID: bbe922eafac6
Revises: 16ba5c78fa62
Create Date: 2025-07-10 20:35:01.021124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe922eafac6'
down_revision = '16ba5c78fa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('enrollment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('graduation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('extracurricular_activities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('student_id_number', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['student_id_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('student_id_number')
        batch_op.drop_column('achievements')
        batch_op.drop_column('extracurricular_activities')
        batch_op.drop_column('graduation_date')
        batch_op.drop_column('enrollment_date')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('nationality')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('room')
        batch_op.drop_column('days')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
