"""Add cascade delete for student relationships

Revision ID: f001802c6950
Revises: c0ad95607842
Create Date: 2025-06-14 00:57:36.710489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f001802c6950'
down_revision = 'c0ad95607842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendances_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('grades_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('grades_student_id_fkey'), 'students', ['student_id'], ['id'])

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendances_student_id_fkey'), 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
